# Generated by Django 5.1.2 on 2024-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "ingredients",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("weight", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
