# Generated by Django 5.1.2 on 2024-11-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(default="abc.png", upload_to="product-images/"),
            preserve_default=False,
        ),
    ]
