# Generated by Django 5.1.2 on 2024-11-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("image", models.ImageField(upload_to="")),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
