# Generated by Django 5.1.2 on 2024-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="categories/"),
        ),
    ]
