# Generated by Django 5.1.2 on 2024-12-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_slider_image_slider_name_sliderimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(upload_to="logo/"),
        ),
    ]
