# Generated by Django 5.1.2 on 2024-10-23 13:45

import django.db.models.deletion
import money.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_bank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VPBank", "VPBank"),
                            ("BIDV", "BIDV"),
                            ("Vietcombank", "Vietcombank"),
                            ("VietinBank", "VietinBank"),
                            ("MBBANK", "MBBANK"),
                            ("ACB", "ACB"),
                            ("SHB", "SHB"),
                            ("Techcombank", "Techcombank"),
                            ("Agribank", "Agribank"),
                            ("HDBank", "HDBank"),
                            ("LienVietPostBank", "LienVietPostBank"),
                            ("VIB", "VIB"),
                            ("SeABank", "SeABank"),
                            ("VBSP", "VBSP"),
                            ("TPBank", "TPBank"),
                            ("OCB", "OCB"),
                            ("MSB", "MSB"),
                            ("Sacombank", "Sacombank"),
                            ("SCB", "SCB"),
                            ("VDB", "VDB"),
                            ("Nam A Bank", "Nam A Bank"),
                            ("ABBANK", "ABBANK"),
                            ("PVcomBank", "PVcomBank"),
                            ("Bac A Bank", "Bac A Bank"),
                            ("UOB", "UOB"),
                            ("Woori", "Woori"),
                            ("HSBC", "HSBC"),
                            ("SCBVL", "SCBVL"),
                            ("PBVN", "PBVN"),
                            ("SHBVN", "SHBVN"),
                            ("NCB", "NCB"),
                            ("VietABank", "VietABank"),
                            ("Viet Capital Bank", "Viet Capital Bank"),
                            ("DongA Bank", "DongA Bank"),
                            ("Vietbank", "Vietbank"),
                            ("ANZVL", "ANZVL"),
                            ("OceanBank", "OceanBank"),
                            ("CIMB", "CIMB"),
                            ("Kienlongbank", "Kienlongbank"),
                            ("IVB", "IVB"),
                            ("BAOVIET Bank", "BAOVIET Bank"),
                            ("SAIGONBANK", "SAIGONBANK"),
                            ("Co-opBank", "Co-opBank"),
                            ("GPBank", "GPBank"),
                            ("VRB", "VRB"),
                            ("CB", "CB"),
                            ("HLBVN", "HLBVN"),
                            ("PG Bank", "PG Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(blank=True, max_length=20)),
                ("the_beneficiarys_name", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_cancelled",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(money.models.get_sentinal_order),
                        related_name="admin_cancelled",
                        to="orders.order",
                    ),
                ),
                (
                    "change",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(money.models.get_sentinal_order),
                        related_name="change",
                        to="orders.order",
                    ),
                ),
                (
                    "customer_cancelled",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(money.models.get_sentinal_order),
                        related_name="customer_cancelled",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BalanceFluctuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_fluctuations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reason",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="money.reason"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_bank",
                    models.CharField(
                        choices=[
                            ("VPBank", "VPBank"),
                            ("BIDV", "BIDV"),
                            ("Vietcombank", "Vietcombank"),
                            ("VietinBank", "VietinBank"),
                            ("MBBANK", "MBBANK"),
                            ("ACB", "ACB"),
                            ("SHB", "SHB"),
                            ("Techcombank", "Techcombank"),
                            ("Agribank", "Agribank"),
                            ("HDBank", "HDBank"),
                            ("LienVietPostBank", "LienVietPostBank"),
                            ("VIB", "VIB"),
                            ("SeABank", "SeABank"),
                            ("VBSP", "VBSP"),
                            ("TPBank", "TPBank"),
                            ("OCB", "OCB"),
                            ("MSB", "MSB"),
                            ("Sacombank", "Sacombank"),
                            ("SCB", "SCB"),
                            ("VDB", "VDB"),
                            ("Nam A Bank", "Nam A Bank"),
                            ("ABBANK", "ABBANK"),
                            ("PVcomBank", "PVcomBank"),
                            ("Bac A Bank", "Bac A Bank"),
                            ("UOB", "UOB"),
                            ("Woori", "Woori"),
                            ("HSBC", "HSBC"),
                            ("SCBVL", "SCBVL"),
                            ("PBVN", "PBVN"),
                            ("SHBVN", "SHBVN"),
                            ("NCB", "NCB"),
                            ("VietABank", "VietABank"),
                            ("Viet Capital Bank", "Viet Capital Bank"),
                            ("DongA Bank", "DongA Bank"),
                            ("Vietbank", "Vietbank"),
                            ("ANZVL", "ANZVL"),
                            ("OceanBank", "OceanBank"),
                            ("CIMB", "CIMB"),
                            ("Kienlongbank", "Kienlongbank"),
                            ("IVB", "IVB"),
                            ("BAOVIET Bank", "BAOVIET Bank"),
                            ("SAIGONBANK", "SAIGONBANK"),
                            ("Co-opBank", "Co-opBank"),
                            ("GPBank", "GPBank"),
                            ("VRB", "VRB"),
                            ("CB", "CB"),
                            ("HLBVN", "HLBVN"),
                            ("PG Bank", "PG Bank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("the_beneficiarys_name", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reason",
            name="withdrawal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(money.models.get_sentinal_withdrawal_request),
                to="money.withdrawalrequest",
            ),
        ),
        migrations.CreateModel(
            name="WithdrawalRequestStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "waiting"),
                            ("customer_cancelled", "customer_cancelled"),
                            ("admin_refused", "admin_refused"),
                            ("accepted", "accepted"),
                            ("completed", "completed"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "withdrawal_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="money.withdrawalrequest",
                    ),
                ),
            ],
        ),
    ]
