# Generated by Django 5.1.2 on 2024-10-24 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="withdrawal_amount",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="withdrawalrequeststatus",
            name="withdrawal_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wr_statuses",
                to="money.withdrawalrequest",
            ),
        ),
    ]
