# Generated by Django 5.1.2 on 2024-11-17 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("money", "0005_alter_balancefluctuation_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("waiting", "waiting"),
                    ("customer_cancelled", "customer_cancelled"),
                    ("admin_refused", "admin_refused"),
                    ("accepted", "accepted"),
                    ("completed", "completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequeststatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "waiting"),
                    ("customer_cancelled", "customer_cancelled"),
                    ("admin_refused", "admin_refused"),
                    ("accepted", "accepted"),
                    ("completed", "completed"),
                ],
                max_length=20,
            ),
        ),
    ]
