# Generated by Django 5.1.2 on 2024-11-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_user_alter_orderstatus_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unpaid", "unpaid"),
                    ("paid", "paid"),
                    ("customer_cancelled", "customer_cancelled"),
                    ("admin_cancelled", "admin_cancelled"),
                    ("accepted", "accepted"),
                    ("done_shipped", "done_shipped"),
                    ("completed", "completed"),
                ],
                max_length=20,
            ),
        ),
    ]
