# Generated by Django 5.1.2 on 2024-11-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "unpaid"),
                    ("paid", "paid"),
                    ("customer_cancelled", "customer_cancelled"),
                    ("admin_cancelled", "admin_cancelled"),
                    ("accepted", "accepted"),
                    ("done_shipped", "done_shipped"),
                    ("completed", "completed"),
                ],
                max_length=20,
            ),
        ),
    ]
