# Generated by Django 5.1.2 on 2024-11-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_message_alter_orderstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedproduct",
            name="name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="orderedproduct",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderedproduct",
            name="total_money",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
