# Generated by Django 5.1.2 on 2024-11-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0006_alter_orderedproduct_name_alter_orderedproduct_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="message",
        ),
    ]
