# Generated by Django 5.1.2 on 2024-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_order_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
    ]
