# Generated by Django 5.1.2 on 2024-12-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatus",
            name="displayed_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
