# Generated by Django 5.1.2 on 2024-12-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_orderstatus_displayed_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderstatus",
            name="displayed_status",
        ),
    ]
