# Generated by Django 5.1.2 on 2024-11-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_cart_chosen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="chosen",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
