# Generated by Django 5.1.2 on 2024-10-23 13:45

import django.db.models.deletion
import user.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        validators=[user.validators.has_number_validator],
                    ),
                ),
                ("phone_number", models.BigIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("psid", models.CharField(blank=True, max_length=20)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("stranger", "stranger"),
                            ("new_customer", "new_customer"),
                            ("regular_customer", "regular_customer"),
                            ("strategic_partner", "strategic_partner"),
                            (
                                "comprehensive_strategic_partner",
                                "comprehensive_strategic_partner",
                            ),
                        ],
                        default="stranger",
                        max_length=35,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
