# Generated by Django 5.1.2 on 2024-11-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default-avatar.png", upload_to=""),
        ),
    ]
