# Generated by Django 5.1.2 on 2024-11-06 07:12

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(
                        validators=[user.models.level_validator]
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "purchased_amount",
                    models.PositiveIntegerField(
                        validators=[user.models.purchased_amount_validator]
                    ),
                ),
            ],
        ),
    ]
