# Generated by Django 5.1.2 on 2024-11-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_profile_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="level",
        ),
    ]
