# Generated by Django 5.1.2 on 2024-11-06 08:07

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_remove_profile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.ForeignKey(
                default=user.models.get_min_level,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.level",
            ),
        ),
    ]
