# Generated by Django 5.1.2 on 2024-11-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_profile_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="level",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="level",
            name="avatar_frame",
            field=models.ImageField(blank=True, null=True, upload_to="frames/"),
        ),
        migrations.AddField(
            model_name="level",
            name="displayed_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="level",
            name="outline_frame",
            field=models.ImageField(blank=True, null=True, upload_to="frames/"),
        ),
    ]
