# Generated by Django 5.1.2 on 2024-11-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_level_level_alter_level_purchased_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
