# Generated by Django 5.1.2 on 2024-11-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_alter_level_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
