# Generated by Django 5.1.2 on 2024-11-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_alter_level_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="level",
            field=models.PositiveIntegerField(),
        ),
    ]
