# Generated by Django 5.1.2 on 2024-11-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_level_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="detail_avatar_frame",
            field=models.ImageField(blank=True, null=True, upload_to="frames/"),
        ),
    ]
