# Generated by Django 5.1.2 on 2024-10-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="success",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
